import * as ns from './own-property-keys-binding-types.js';
export var a_local1;
var local2;
export {local2 as b_renamed};
export {a_local1 as e_indirect} from './own-property-keys-binding-types.js';
export * from './own-property-keys-binding-types_FIXTURE.js';
var stringKeys = Object.getOwnPropertyNames(ns);
var symbolKeys = Object.getOwnPropertySymbols(ns);
var allKeys = Reflect.ownKeys(ns);
export let c_localUninit1;
let localUninit2;
export {localUninit2 as d_renamedUninit};
export {c_localUninit1 as f_indirectUninit} from './own-property-keys-binding-types.js';
export default null;