import * as ns from './get-own-property-str-found-init.js';
export var local1 = 201;
var local2 = 207;
export {local2 as renamed};
export {local1 as indirect} from './get-own-property-str-found-init.js';
export default 302;
var desc;
desc = Object.getOwnPropertyDescriptor(ns, 'local1');
desc = Object.getOwnPropertyDescriptor(ns, 'renamed');
desc = Object.getOwnPropertyDescriptor(ns, 'indirect');
desc = Object.getOwnPropertyDescriptor(ns, 'default');